version: '2'
services:
  myztl6-app:
    image: myztl6
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://myztl6-postgresql:5432/myztl6
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  myztl6-postgresql:
    extends:
      file: postgresql.yml
      service: myztl6-postgresql
